# Generated by Django 3.2.16 on 2023-05-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security_Risk_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Infrastructure Questionnaire', 'Infrastructure Questionnaire'), ('Hardware Risk', 'Hardware Risk'), ('Software Risk', 'Software Risk'), ('User Risk', 'User Risk'), ('Assessment Result', 'Assessment Result')], max_length=100)),
                ('total_number_of_questions', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
