# Generated by Django 3.2.16 on 2023-05-02 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_risk_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1500)),
                ('assessment_number', models.CharField(max_length=500)),
                ('active_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PASSIVE', 'PASSIVE')], max_length=100)),
                ('risk_group', models.CharField(max_length=150)),
                ('asset_type', models.CharField(max_length=50)),
                ('question_group', models.CharField(max_length=850)),
                ('question_type', models.CharField(max_length=50)),
                ('value_type', models.CharField(max_length=150)),
                ('question_number', models.CharField(max_length=100)),
                ('threat_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user_answer', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Answers',
            },
        ),
        migrations.CreateModel(
            name='Risk_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1500)),
                ('asset_type', models.CharField(choices=[('COMPANY HARDWARE', 'COMPANY HARDWARE'), ('USER ELECTRONICS', 'USER ELECTRONICS'), ('IoT', 'IoT'), ('THIRD-PARTY SOFTWARE', 'THIRD-PARTY SOFTWARE'), ('SOFTWARE HOSTED on ORGANIZATION MACHINES', 'SOFTWARE HOSTED on ORGANIZATION MACHINES'), ('INTERNAL USER', 'INTERNAL USER'), ('EXTERNAL USER', 'EXTERNAL USER')], max_length=50)),
                ('question_type', models.CharField(choices=[('LIKELIHOOD', 'LIKELIHOOD'), ('IMPACT', 'IMPACT'), ('GENERAL', 'GENERAL'), ('EXT', 'EXT')], max_length=50)),
                ('question_group', models.CharField(max_length=850)),
                ('value_type', models.CharField(choices=[('VULNERABILTY', 'VULNERABILTY'), ('THREAT', 'THREAT'), ('IMPACT', 'IMPACT'), ('ASSET', 'ASSET')], max_length=50)),
                ('question_number', models.CharField(max_length=100)),
                ('threat_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('suggestion', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('risk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_risk_categories.security_risk_category')),
            ],
            options={
                'verbose_name_plural': 'Security Risk Questions',
            },
        ),
        migrations.CreateModel(
            name='Risk_Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_number', models.CharField(max_length=500)),
                ('active_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PASSIVE', 'PASSIVE')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Security Risk Assessment',
            },
        ),
    ]
