# Generated by Django 3.2.16 on 2023-04-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=250)),
                ('question_group', models.CharField(max_length=250)),
                ('user_answer', models.CharField(max_length=250)),
                ('question_number', models.CharField(max_length=150)),
                ('user_accept_condition', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Survey Answers',
            },
        ),
        migrations.CreateModel(
            name='Survey_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question_group', models.CharField(max_length=250)),
                ('question_number', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Survey Questions',
            },
        ),
    ]
